name: MCarcinizer
main: com.kraby.mcarcinizer.CarcinizerMain
version: 3.0.3
api-version: 1.15
description: Carcinerize everything
author: Kraby
commands:
  carcreload:
    description: Reloads all MCarcinizer subplugins.
    usage: /carcreload
    permission: carc.reload
  invsize:
    description: View inventory size (useful for config balancing)
    usage: /invsize
    permission: carc.invsize