name: HealthHardcorizer
main: com.kraby.healthhardcorizer.MainHH
version: 2.0
api-version: 1.15
depend: [Kurabase]
description: Edit health and hunger mechanics
author: Kraby
commands:
  hhreload:
    description: Reloads the HealthHardcorizer plugin
    usage: /hhreload
    permission: healthhardcorizer.reload
  hhinfo:
    description: (debug) Display player info
    usage: /hhinfo
    permission: healthhardcorizer.info