deathkeeper:
    enabled: true
    
    eternal_keeper_level: 200
    
    damage:
        base: 2
        factor: 0.2
    
    life:
        base: 4
        factor: 1
    
    movement_speed:
        base: 0.15
        factor: 0.0025
        max: 0.4